version: '2'
services:
    oficialia_electoral-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/oficialia_electoral/mongodb/:/data/db/
